### ISSUE TITLE
CD example source code "AI Techniques for Game Programming"

### ISSUE THREAD

**Issue by John3** [crazyskady/ai-game-python#1]
Hello :)

Hey Crazy Skady can you share the original CD source code of "AI Techniques for Game Programming by Matt". I bought used and don't have the CD. In the author site don't have any link to download the source code example. T_T

Can you help me :) Thank you!

regards
J

**Comment by crazyskady** [comment]
Hi, John

Absolutely, give me an email, I will email it to you. :)

BR/Wei

**Comment by John3** [comment]
Hi!

just a casualness but Mat answered my email today :D he send me a link.

Thank you crazyskady.

**Comment by John3** [comment]
by the way I forked you repo just for study :) thanks

**Comment by crazyskady** [comment]
:) You are always welcome.
